// ============================================================
// NOVARA SHOWROOM — CONTENT DATA
// Swap `videoSrc` with a real transparent-alpha .webm path
// (e.g. /assets/videos/headphone.webm) to use real 360° footage.
// Until then, products render as procedurally-styled holo-discs.
// ============================================================

const CATEGORIES = [
  { id: "gaming",        name: "Gaming",        icon: "fa-solid fa-gamepad",          count: 24 },
  { id: "tech",          name: "Tech",          icon: "fa-solid fa-microchip",         count: 41 },
  { id: "lifestyle",     name: "Lifestyle",     icon: "fa-solid fa-mug-hot",           count: 18 },
  { id: "accessories",   name: "Accessories",   icon: "fa-solid fa-headphones-simple", count: 33 },
  { id: "photography",   name: "Photography",   icon: "fa-solid fa-camera",            count: 12 },
  { id: "travel",        name: "Travel",        icon: "fa-solid fa-plane",             count: 9  },
  { id: "smart-home",    name: "Smart Home",    icon: "fa-solid fa-house-signal",      count: 15 },
];

const PRODUCTS = [
  {
    id: "p1",
    name: "Aria Pro Earbuds",
    category: "Accessories",
    rating: 4.8,
    reviews: 1204,
    price: 179,
    color: "#ff6a00",
    shape: "earbuds",
    desc: "Adaptive noise cancellation tuned in an anechoic chamber, with a case that charges in your pocket. Built for people who forget they're wearing them.",
    specs: [
      { label: "Battery", value: "32 hrs (case incl.)" },
      { label: "Driver", value: "11mm dynamic" },
      { label: "ANC", value: "Adaptive, 3-mic" },
      { label: "Weight", value: "4.4g per bud" },
    ],
  },
  {
    id: "p2",
    name: "Crest Studio Headphone",
    category: "Tech",
    rating: 4.9,
    reviews: 856,
    price: 329,
    color: "#ffb000",
    shape: "headphone",
    desc: "Over-ear comfort with studio-grade flat response. Memory foam ear cups and a 60-hour battery for sessions that don't end when the train does.",
    specs: [
      { label: "Battery", value: "60 hrs" },
      { label: "Driver", value: "40mm planar" },
      { label: "Connectivity", value: "Bluetooth 5.4 / 3.5mm" },
      { label: "Weight", value: "248g" },
    ],
  },
  {
    id: "p3",
    name: "Pulse Watch X2",
    category: "Lifestyle",
    rating: 4.6,
    reviews: 642,
    price: 249,
    color: "#ff6a00",
    shape: "watch",
    desc: "A titanium case, sapphire glass, and a heart-rate sensor accurate enough for a cardiologist. Seven-day battery, zero compromises.",
    specs: [
      { label: "Case", value: "Titanium, 44mm" },
      { label: "Battery", value: "7 days" },
      { label: "Water rating", value: "10 ATM" },
      { label: "Display", value: "AMOLED, always-on" },
    ],
  },
  {
    id: "p4",
    name: "Beam X1 Tactical Torch",
    category: "Travel",
    rating: 4.7,
    reviews: 311,
    price: 89,
    color: "#ffb000",
    shape: "torch",
    desc: "1200 lumens from something the size of a marker. Machined aircraft-grade aluminum, IP68 rated, drops without complaint.",
    specs: [
      { label: "Output", value: "1200 lumens" },
      { label: "Runtime", value: "4 hrs (high)" },
      { label: "Rating", value: "IP68" },
      { label: "Material", value: "Aircraft aluminum" },
    ],
  },
  {
    id: "p5",
    name: "Vector GT Gaming Mouse",
    category: "Gaming",
    rating: 4.8,
    reviews: 1532,
    price: 129,
    color: "#ff6a00",
    shape: "mouse",
    desc: "26,000 DPI optical sensor, 0 click latency, and a shell shaved down to 58 grams. Built with esports players, not for them.",
    specs: [
      { label: "Sensor", value: "26,000 DPI" },
      { label: "Weight", value: "58g" },
      { label: "Switches", value: "Optical, 100M clicks" },
      { label: "Polling rate", value: "8000Hz" },
    ],
  },
  {
    id: "p6",
    name: "Skyhover Mini Drone",
    category: "Photography",
    rating: 4.5,
    reviews: 278,
    price: 599,
    color: "#ffb000",
    shape: "drone",
    desc: "Folds into your palm, flies for 34 minutes, and shoots 4K stabilized footage that doesn't look like a drone shot it.",
    specs: [
      { label: "Camera", value: "4K / 60fps" },
      { label: "Flight time", value: "34 min" },
      { label: "Range", value: "10km" },
      { label: "Folded size", value: "140mm" },
    ],
  },
  {
    id: "p7",
    name: "Forge Mechanical Keyboard",
    category: "Gaming",
    rating: 4.9,
    reviews: 967,
    price: 189,
    color: "#ff6a00",
    shape: "keyboard",
    desc: "Hot-swappable switches, a gasket-mounted plate, and a sound profile people record videos of. CNC aluminum, no flex.",
    specs: [
      { label: "Switches", value: "Hot-swap, 5-pin" },
      { label: "Layout", value: "75% gasket mount" },
      { label: "Connectivity", value: "Wired / 2.4GHz / BT" },
      { label: "Case", value: "CNC aluminum" },
    ],
  },
  {
    id: "p8",
    name: "Monolith Smart Speaker",
    category: "Smart Home",
    rating: 4.6,
    reviews: 489,
    price: 219,
    color: "#ffb000",
    shape: "speaker",
    desc: "Room-filling sound from a cylinder you'll actually want on display. Auto-tunes itself to your room in under a minute.",
    specs: [
      { label: "Output", value: "360° / 60W" },
      { label: "Room calibration", value: "Automatic" },
      { label: "Connectivity", value: "WiFi 6 / BT 5.3" },
      { label: "Voice assistant", value: "Built-in" },
    ],
  },
  {
    id: "p9",
    name: "Slate Pro Laptop",
    category: "Tech",
    rating: 4.8,
    reviews: 1109,
    price: 1799,
    color: "#ff6a00",
    shape: "laptop",
    desc: "A 14-inch canvas at 120Hz, all-day battery, and a chassis machined from a single aluminum billet. Fast enough to forget it's thin.",
    specs: [
      { label: "Display", value: "14\" 120Hz OLED" },
      { label: "Battery", value: "Up to 19 hrs" },
      { label: "Build", value: "Unibody aluminum" },
      { label: "Weight", value: "1.3kg" },
    ],
  },
  {
    id: "p10",
    name: "Horizon Phone 7",
    category: "Tech",
    rating: 4.7,
    reviews: 2031,
    price: 999,
    color: "#ffb000",
    shape: "phone",
    desc: "A camera system that shoots in the dark, a screen that survives your pocket, and a battery that survives your day. Twice.",
    specs: [
      { label: "Display", value: "6.7\" 120Hz" },
      { label: "Camera", value: "Triple, 50MP main" },
      { label: "Battery", value: "5200mAh" },
      { label: "Build", value: "Titanium frame" },
    ],
  },
];

const PROMOS = [
  {
    id: "promo1",
    tag: "Showroom Exclusive",
    title: "Aria Pro, redesigned.",
    sub: "The second generation earbuds — now with 32 hours of battery and a case that disappears into your pocket.",
    cta: "Shop Aria Pro",
    color: "#ff6a00",
  },
  {
    id: "promo2",
    tag: "Limited Run",
    title: "Forge Keyboard — Obsidian Edition",
    sub: "200 units. Matte black anodized aluminum, sold only through the virtual showroom.",
    cta: "View Obsidian Edition",
    color: "#ffb000",
  },
  {
    id: "promo3",
    tag: "Trade-In Event",
    title: "Upgrade your Slate. We'll take the old one.",
    sub: "Trade any laptop, get up to $400 off Slate Pro through the end of the month.",
    cta: "Check Trade-In Value",
    color: "#ff6a00",
  },
];

const JOURNAL = [
  {
    id: "j1",
    date: "Jun 18, 2026",
    category: "Engineering",
    headline: "Inside the anechoic chamber where Aria Pro was tuned",
    thumb: "headphones",
  },
  {
    id: "j2",
    date: "Jun 11, 2026",
    category: "Showroom",
    headline: "We rebuilt the virtual showroom's lighting engine from scratch",
    thumb: "showroom",
  },
  {
    id: "j3",
    date: "May 29, 2026",
    category: "Product",
    headline: "Why Forge's gasket mount took fourteen prototypes",
    thumb: "keyboard",
  },
  {
    id: "j4",
    date: "May 14, 2026",
    category: "Culture",
    headline: "Meet the three people who choose every material Novara ships",
    thumb: "team",
  },
];
